---

- name: Disable amazon-id YUM plugin
  lineinfile:
    dest: /etc/yum/pluginconf.d/amazon-id.conf
    regexp: "^enabled="
    line: "enabled=0"
  register: disable_plugin_amazon_id
  become: yes

- name: Disable rhui-lb YUM plugin
  lineinfile:
    dest: /etc/yum/pluginconf.d/rhui-lb.conf
    regexp: "^enabled="
    line: "enabled=0"
  register: disable_plugin_rhui_lb
  become: yes

- name: Stop choose_repo service
  service:
    name: choose_repo
    state: stopped
  become: yes

- name: Disable choose_repo service
  service:
    name: choose_repo
    enabled: no
  become: yes

- name: Find RHUI repositories
  find:
    paths: /etc/yum.repos.d
    patterns:
      - "*rhui*.repo"
      - "*rhui*.conf"
  become: yes
  register: rhsm_find_rhui_repos

- name: Disable RHUI repositories
  command: mv "{{ item.path }}" "{{ item.path }}.bak"
  loop: "{{ rhsm_find_rhui_repos.files }}"
  become: yes
